
import com.mysql.cj.jdbc.MysqlDataSource;
import java.sql.Statement;
import java.util.ArrayList;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class MAINPAGE extends javax.swing.JFrame {
 byte[] pimg =null;

    /**
     * Creates new form MAINPAGE
     */
        Integer imgIndex = 0;
    public MAINPAGE() {
        initComponents();
    }
    Displayevent de =new Displayevent();
Connection conn;
     PreparedStatement pst = null;
     ResultSet rs;
     
    public Connection createConnection(){
        
          try {
              Connection myConnection = null;
              
              MysqlDataSource datasource = new MysqlDataSource();
              
              datasource.setServerName("localhost");
              datasource.setPortNumber(3306);
              datasource.setUser("root");
              datasource.setPassword("Parthavi@1204");
              datasource.setDatabaseName("databaseforimageslider");
              
              
              myConnection = datasource.getConnection();
              
              
              return myConnection;
          } catch (SQLException ex) {
              Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
          }
          return null;
   
    }
public ArrayList<byte[]> getImagesList(){
        
        ArrayList<byte[]> imgList = new ArrayList<>();
        
        Connection con = createConnection();
        
        Statement st;
        ResultSet rs;
        
        try {
            
            st = con.createStatement();
            rs = st.executeQuery("SELECT Images FROM tableforimageslider");
            
            while(rs.next()){
                
               imgList.add(rs.getBytes("Images")); 
               
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DashboardforUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return imgList;
    }
      public void showImage(Integer index){
        
        Image img = new ImageIcon(getImagesList().get(index)).getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH);
        label1.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        searchdata = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        vpimg1 = new javax.swing.JLabel();
        vpimg2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        simg2 = new javax.swing.JLabel();
        simg1 = new javax.swing.JLabel();
        plabel = new javax.swing.JLabel();
        vp1label = new javax.swing.JLabel();
        vp2label = new javax.swing.JLabel();
        s1label = new javax.swing.JLabel();
        s2label = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kGradientPanel11 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 0, 0));
        kGradientPanel3.setkGradientFocus(1000);
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 255, 0));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/WhatsApp_Image_2023-08-26_at_23.10.39-removebg-preview.png"))); // NOI18N
        kGradientPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 100));

        jLabel6.setFont(new java.awt.Font("Prompt Black", 0, 24)); // NOI18N
        jLabel6.setText("COMMITEE");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, 40));

        jLabel7.setFont(new java.awt.Font("Prompt Black", 0, 24)); // NOI18N
        jLabel7.setText("HOME");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        kGradientPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 80, 40));

        jLabel2.setFont(new java.awt.Font("Prompt Black", 0, 24)); // NOI18N
        jLabel2.setText("FEEDBACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        kGradientPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 130, 40));

        jLabel10.setFont(new java.awt.Font("Prompt Black", 0, 24)); // NOI18N
        jLabel10.setText("MY PROFILE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        kGradientPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, 40));

        jLabel4.setFont(new java.awt.Font("Prompt Black", 0, 24)); // NOI18N
        jLabel4.setText("EVENTS");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        kGradientPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 40));

        kGradientPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 710));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 740, 140));

        kGradientPanel12.setkEndColor(new java.awt.Color(255, 0, 0));
        kGradientPanel12.setkGradientFocus(1000);
        kGradientPanel12.setkStartColor(new java.awt.Color(255, 255, 0));
        kGradientPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-next-page-45.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        kGradientPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, 40));

        label1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        kGradientPanel12.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 435, 96));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-next-page-45 (1).png"))); // NOI18N
        jLabel8.setText("jLabel5");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        kGradientPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 50, 40));

        jTabbedPane3.addTab("tab5", kGradientPanel12);

        kGradientPanel9.setkEndColor(new java.awt.Color(255, 204, 0));
        kGradientPanel9.setkStartColor(new java.awt.Color(255, 51, 0));
        kGradientPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("E");
        kGradientPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 66, 43, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title ", "Summary", "Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        kGradientPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 700, 300));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdataActionPerformed(evt);
            }
        });
        jPanel3.add(searchdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 220, 35));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-35.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 44, 41));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Showdata");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 35));

        kGradientPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 50));

        jTabbedPane3.addTab("tab2", kGradientPanel9);

        kGradientPanel10.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel10.setkGradientFocus(100);
        kGradientPanel10.setkStartColor(new java.awt.Color(255, 51, 0));

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 51, 0));
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 153, 0));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Data Science Student Association");
        kGradientPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 85, 94));

        vpimg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(vpimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 90, 94));

        vpimg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(vpimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 85, 94));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setText("President");
        kGradientPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setText("Vice-President");
        kGradientPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 30));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel15.setText("Vice-President");
        kGradientPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel16.setText("Secretary");
        kGradientPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        simg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(simg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 76, 88));

        simg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(simg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 76, 88));

        plabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(plabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 19));

        vp1label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(vp1label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 20));

        vp2label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(vp2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 150, 19));

        s1label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(s1label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 150, 18));

        s2label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.add(s2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 445, 140, 20));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel17.setText("Secretary");
        kGradientPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        kGradientPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 560, 226));

        jScrollPane1.setViewportView(kGradientPanel4);

        javax.swing.GroupLayout kGradientPanel10Layout = new javax.swing.GroupLayout(kGradientPanel10);
        kGradientPanel10.setLayout(kGradientPanel10Layout);
        kGradientPanel10Layout.setHorizontalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        kGradientPanel10Layout.setVerticalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab3", kGradientPanel10);

        kGradientPanel11.setkEndColor(new java.awt.Color(255, 51, 0));
        kGradientPanel11.setkGradientFocus(1000);
        kGradientPanel11.setkStartColor(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout kGradientPanel11Layout = new javax.swing.GroupLayout(kGradientPanel11);
        kGradientPanel11.setLayout(kGradientPanel11Layout);
        kGradientPanel11Layout.setHorizontalGroup(
            kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        kGradientPanel11Layout.setVerticalGroup(
            kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab4", kGradientPanel11);

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 204, 0));
        kGradientPanel2.setkGradientFocus(800);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 153, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane3.addTab("tab1", kGradientPanel2);

        kGradientPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 740, 600));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        imgIndex--;

        if(imgIndex < 0){

            imgIndex = 0;

        }

        showImage(imgIndex);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        imgIndex++;

        if(imgIndex >= getImagesList().size()){

            imgIndex = getImagesList().size() - 1;

        }

        showImage(imgIndex);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(0);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(2);
         try {                                         
                      // TODO add your handling code here:
                      String SUrl,SUser,SPass;
                      SUrl = "jdbc:MySQL://localhost:3306/connector";
                      SUser = "root";
                      SPass = "Parthavi@1204";
            try {
                              Class.forName("com.mysql.cj.jdbc.Driver");
                      conn = DriverManager.getConnection(SUrl,SUser,SPass);
                      
                      String sql = "SELECT * FROM committee ";
                       pst = conn.prepareStatement(sql);
                       
                       rs = pst.executeQuery();
                       if(rs.next()){
                           
                           String Name1 = rs.getString("Name");
                          plabel.setText(Name1);
                           String Name2 = rs.getString("Vpname1");
                          vp1label.setText(Name2);
                           String Name3 = rs.getString("Vpname2");
                         vp2label.setText(Name3);
                           String Name4 = rs.getString("Sname1");
                          s1label.setText(Name4);
                           String Name5 = rs.getString("Sname2");
                          s2label.setText(Name5);
                          String Others1 = rs.getString("Others");
                          jTextArea1.setText(Others1);
                                            byte[] img0 = rs.getBytes("Image");
                            ImageIcon image0 = new ImageIcon(img0);
                Image im0 = image0.getImage();
                Image myimg0 = im0.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImag0e = new ImageIcon(myimg0);
                img.setIcon(newImag0e);
              byte[] img1 = rs.getBytes("VpImage1");
                            ImageIcon image1 = new ImageIcon(img1);
                Image im1 = image1.getImage();
                Image myimg1 = im1.getScaledInstance(vpimg1.getWidth(), vpimg1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImag1e = new ImageIcon(myimg1);
                vpimg1.setIcon(newImag1e);
                  byte[] img2 = rs.getBytes("VpImage2");
                            ImageIcon image2 = new ImageIcon(img2);
                Image im2 = image2.getImage();
                Image myimg2 = im2.getScaledInstance(vpimg2.getWidth(), vpimg2.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage2 = new ImageIcon(myimg2);
                vpimg2.setIcon(newImage2);
                 byte[] img3 = rs.getBytes("SImage1");
                            ImageIcon image3 = new ImageIcon(img3);
                Image im3 = image3.getImage();
                Image myimg3 = im3.getScaledInstance(simg1.getWidth(), simg1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage3 = new ImageIcon(myimg3);
                simg1.setIcon(newImage3);
                 byte[] img4 = rs.getBytes("SImage2");
                            ImageIcon image4 = new ImageIcon(img4);
                Image im4 = image4.getImage();
                Image myimg4 = im4.getScaledInstance(simg2.getWidth(), simg2.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage4 = new ImageIcon(myimg4);
                simg2.setIcon(newImage4);
                       } 
          } catch (ClassNotFoundException ex) {
                              Logger.getLogger(MAINPAGE.class.getName()).log(Level.SEVERE, null, ex);
                          }
                  } catch (SQLException ex) {
                      Logger.getLogger(MAINPAGE.class.getName()).log(Level.SEVERE, null, ex);
                 
                  }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(4);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void searchdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchdataActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
try {                                         
                      // TODO add your handling code here:
                      String SUrl,SUser,SPass;
                      SUrl = "jdbc:MySQL://localhost:3306/connector";
                      SUser = "root";
                      SPass = "Parthavi@1204";
            try {
                              Class.forName("com.mysql.cj.jdbc.Driver");
                      conn = DriverManager.getConnection(SUrl,SUser,SPass);
                      
                      String sql = "SELECT * FROM connector where Title=?";
                       pst = conn.prepareStatement(sql);
                       pst.setString(1, searchdata.getText());
                       rs = pst.executeQuery();
                       if(rs.next()){
                            de.setVisible(true);
       de.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      
                           String Title1 = rs.getString("Title");
                           de.jTitle1.setText(Title1);
                           String Summary1 = rs.getString("Summary");
                           de.jTextArea1.setText(Summary1);
                           String date1 = rs.getString("date");
                           de.jdate1.setText(date1);
                           String Status1 = rs.getString("Status");
                           de.jStatus1.setText(Status1);
                            byte[] img = rs.getBytes("Image");
                            ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myimg = im.getScaledInstance(de.jimg1.getWidth(), de.jimg1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myimg);
                de.jimg1.setIcon(newImage);
              
              
                       } 
          } catch (ClassNotFoundException ex) {
                              Logger.getLogger(Events.class.getName()).log(Level.SEVERE, null, ex);
                          }
                  } catch (SQLException ex) {
                      Logger.getLogger(Events.class.getName()).log(Level.SEVERE, null, ex);
                 
                  }       
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       try {                                         
                      // TODO add your handling code here:
                      
                      
                      String SUrl,SUser,SPass;
                      SUrl = "jdbc:MySQL://localhost:3306/connector";
                      SUser = "root";
                      SPass = "Parthavi@1204";
                      
                      
                          Class.forName("com.mysql.cj.jdbc.Driver");
                     
                      
                      
                      
                      conn = DriverManager.getConnection(SUrl,SUser,SPass);
                      
                      String sql = "SELECT * FROM connector";
                      
                      pst = conn.prepareStatement(sql);
                      rs = pst.executeQuery(sql);
                      
                      
                      
                      
                      try {
                          while(rs.next()){
                              String Title = rs.getString("Title");
                              
                              
                               String Summary = rs.getString("Summary");
                              
                              String date = String.valueOf(rs.getInt("date"));
                     
                              
                                String  Status = rs.getString("Status");
                              
                             
                               String tbData[] = {Title,Summary,date,Status,};
                        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                       model.addRow(tbData);
                          }
                      } catch (SQLException ex) {
                          Logger.getLogger(Eventsforuser.class.getName()).log(Level.SEVERE, null, ex);
                      }
                      
                      
                  } catch (SQLException ex) {
                      Logger.getLogger(Eventsforuser.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (ClassNotFoundException ex) {
            Logger.getLogger(Eventsforuser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINPAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel img;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextArea jTextArea1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel11;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JLabel label1;
    public javax.swing.JLabel plabel;
    public javax.swing.JLabel s1label;
    public javax.swing.JLabel s2label;
    private javax.swing.JTextField searchdata;
    public javax.swing.JLabel simg1;
    public javax.swing.JLabel simg2;
    public javax.swing.JLabel vp1label;
    public javax.swing.JLabel vp2label;
    public javax.swing.JLabel vpimg1;
    public javax.swing.JLabel vpimg2;
    // End of variables declaration//GEN-END:variables
}
